{
 "title": "ToDo Task Manager",
 "tags": [
  "elixir",
  "phoenix",
  "todo"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Avg Response Time (ms)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(todo_task_manager_prom_ex_phoenix_http_request_duration_milliseconds_sum[1m])) / sum(rate(todo_task_manager_prom_ex_phoenix_http_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(todo_task_manager_prom_ex_phoenix_http_requests_total{status=~\"2..\"}[1m])) / sum(rate(todo_task_manager_prom_ex_phoenix_http_requests_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(todo_task_manager_prom_ex_phoenix_http_requests_total{status=~\"4..|5..\"}[1m])) / sum(rate(todo_task_manager_prom_ex_phoenix_http_requests_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Current RPS (req/s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(todo_task_manager_prom_ex_phoenix_http_requests_total[30s]))"
    }
   ]
  },
  {
   "title": "RPS Growth Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (method, path) (rate(todo_task_manager_prom_ex_phoenix_http_requests_total[30s])))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "P95 Response Time (ms)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(todo_task_manager_prom_ex_phoenix_http_request_duration_milliseconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "p99 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, method, path) (rate(todo_task_manager_prom_ex_phoenix_http_request_duration_milliseconds_bucket[1m])))",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Top API Endpoints",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method, path) (rate(todo_task_manager_prom_ex_phoenix_http_requests_total[30s])))"
    }
   ]
  },
  {
   "title": "Response Status Codes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by (status) (rate(todo_task_manager_prom_ex_phoenix_http_requests_total[1m])))",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}