global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'load-generator'
    static_configs:
      - targets: ['load-generator:8081']

  - job_name: 'todo_task_manager'
    static_configs:
      - targets: ['app:4000']

  - job_name: 'cockroachdb'
    static_configs:
      - targets: ['db:8080']
    metrics_path: '/_status/vars'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
